includes:
  - dynamic-plugins.default.yaml
plugins:
  - package: ./dynamic-plugins/dist/backstage-plugin-techdocs-backend-dynamic
    disabled: true
  - package: ./dynamic-plugins/dist/backstage-plugin-techdocs
    disabled: true
  - disabled: false
    integrity: >-
      sha512-vjlQ9hLDdHwY67E6S3gDQgXBsB/yO5GNuZQltFVxHKY1BGlwGvgSAhoejyN6mgpydGgJlXtM0hFL0vJ9pb6UCQ==
    package: '/opt/app-root/src/local-plugins/ansible-plugin-backstage-rhaap-1.1.0.tgz'
    pluginConfig:
      dynamicPlugins:
        frontend:
          ansible.plugin-backstage-rhaap:
            appIcons:
              - importName: AnsibleLogo
                name: AnsibleLogo
            dynamicRoutes:
              - importName: AnsiblePage
                menuItem:
                  icon: AnsibleLogo
                  text: Ansible
                path: /ansible
  - disabled: false
    integrity: >-
      sha512-ndd3uILlkvZ+jrpNsnYjmwkQY/e71EcCYqjnAsAF3CeZ3aZG/FYgvHFQ5OR9sNQHTaQ+ZjCietH9403xHSNZxQ==
    package: >-
      /opt/app-root/src/local-plugins/ansible-plugin-scaffolder-backend-module-backstage-rhaap-1.1.0.tgz
    pluginConfig:
      dynamicPlugins:
        backend:
          ansible.plugin-scaffolder-backend-module-backstage-rhaap: null
  - disabled: false
    integrity: >-
      sha512-EaBuyPWVpfsSpuWLYPZzIol3CxTqP39dabQmzDZgoVuyFgq8UA4kXyhyyZLNm0B5C+u0Sa/sksKdhqRi/tDLaw==
    package: >-
      /opt/app-root/src/local-plugins/ansible-plugin-backstage-rhaap-backend-1.1.0.tgz
    pluginConfig:
      dynamicPlugins:
        backend:
          ansible.plugin-backstage-rhaap-backend: null
  - disabled: false
    package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-rbac
  # - disabled: false
  #   package: >-
  #     ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-dynamic
  # - disabled: false
  #   package: >-
  #     ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-org-dynamic
  # - disabled: false
  #   package: >-
  #     ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-org
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-plugin-github-actions
  # - disabled: false
  #   package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github


  # EXAMPLES:
  # loading plugin from host directory
  # - package: /opt/app-root/src/local-plugins/todo
  #   disabled: false
  #   pluginConfig:
  #     dynamicPlugins:
  #       frontend:
  #         backstage-community.plugin-todo:
  #           mountPoints:
  #             - mountPoint: entity.page.todo/cards
  #               importName: EntityTodoContent
  #           entityTabs:
  #             - path: /todo
  #               title: Todo
  #               mountPoint: entity.page.todo

  # loading image from container image
  #  - package: oci://docker.io/tomaskral/simple-chat:v0.0.1!internal-backstage-plugin-simple-chat
  #    disabled: false
  #    pluginConfig:
  #      dynamicPlugins:
  #        frontend:
  #            internal.backstage-plugin-simple-chat:
  #              appIcons:
  #                - name: chatIcon
  #                  importName: ChatIcon
  #              dynamicRoutes:
  #                - path: /simple-chat
  #                  importName: SimpleChatPage
  #                  menuItem:
  #                    text: 'Simple Chat'
  #                    icon: chatIcon

  # # loading image from tarball URL
  # - disabled: false
  #   package: >-
  #       https://github.com/redhat-developer/rhdh-plugin-export-backstage-community-plugins/releases/download/v1.2.0/backstage-community-plugin-tech-insights-dynamic-0.3.28.tgz
  #   integrity: sha512-cNHXSwPa5fOi2BcNVSe7tfdLyM0JY988CE5t+P9p/XlboP1QpQbMcLBmqPrlXZdpedAyp81Zz3yPQYGnPuy9ww==
  #   pluginConfig:
  #     dynamicPlugins:
  #       techInsights:
  #         factRetrievers:
  #           entityOwnershipFactRetriever:
  #             cadence: '*/15 * * * *'
  #             lifecycle: { timeToLive: { weeks: 2 } }
  #           entityMetadataFactRetriever:
  #             cadence: '*/15 * * * *'
  #             lifecycle: { timeToLive: { weeks: 2 } }
  #           techdocsFactRetriever:
  #             cadence: '*/15 * * * *'
  #             lifecycle: { timeToLive: { weeks: 2 } }
  #           apiDefinitionFactRetriever:
  #             cadence: '*/15 * * * *'
  #     lifecycle: { timeToLive: { weeks: 2 } }

  # # loading plugin from directory inside the RHDH container
  # - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-rbac
  #   disabled: true
  #   pluginConfig:
  #     dynamicPlugins:
  #       frontend:
  #         janus-idp.backstage-plugin-rbac:
  #           mountPoints:
  #             - mountPoint: admin.page.rbac/cards
  #               module: RbacPlugin
  #               importName: RbacPage
  #               config:
  #                 layout:
  #                   gridColumn: "1 / -1"
  #                   width: 100vw
  #                 props:
  #                   useHeader: false
  #           dynamicRoutes:
  #             - path: /admin/rbac
  #               module: RbacPlugin
  #               importName: RbacPage
